base_url = "/"
theme = "papaya"
taxonomies = [
    { name = "tags", rss = true },
    { name = "categories", rss = true },
]

# TODO(norman): Look into enabling this for both English and Japanese
build_search_index = false

[markdown]
highlight_theme = "monokai"

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[languages.en]
title = "Norman's Blog"
description = "Notes and thoughts on software, Japan, and etc."
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
    { name = "tags", rss = true },
    { name = "categories", rss = true },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Posts"
more_blog_posts = "More posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "All tags"
category = "Category"
categories = "Categories"
to_all_categories = "All categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "Newer posts"
next_page = "Older posts"
date_format = "%B %e, %Y"
language_switch_en = "English"
language_switch_ja = "日本語"

[languages.ja]
title = "ノーマンのブログ"
description = "ソフトのブログ"
base_url = "/ja"
taxonomies = [
    { name = "tags", rss = true },
    { name = "categories", rss = true },
]

[languages.ja.translations]
projects = "プロジェクト"
blog = "ブログ"
about = "自己紹介"
recent_projects = "最近のプロジェクト"
more_projects = "その他のプロジェクト"
recent_blog_posts = "最近のブログ記事"
more_blog_posts = "その他のブログ記事"
tag = "タグ"
tags = "タグ"
to_all_tags = "すべてのタグへ"
category = "カテゴリー"
categories = "カテゴリー"
to_all_categories = "すべてのカテゴリへ"
view_by = "表示順"
other = "その他"
minute = "分"
prev_page = "前"
next_page = "つぎ"
date_format = "%B %e, %Y"
language_switch_en = "English"
language_switch_ja = "日本語"

[extra]
menu_items = [
    # { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = true, recent_items = 3, recent_trans_key = "recent_projects", more_trans_key = "more_projects" },
    { name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    # { name = "tags", url = "$LANG_BASE_URL/tags" },
    # { name = "about", url = "$LANG_BASE_URL/about", show_recent = false },
    { name = "language_switch_en", url = "https://normful.com" },
    { name = "language_switch_ja", url = "https://normful.com/ja" },
]
author = "Norman Sue"
site_url = "https://www.normful.com"

[extra.images]
max_width = 2500

[extra.ogp]
locale = "en_US"
first_name = "Norman"
last_name = "Sue"
gender = "male"
username = "normful"

[extra.social]
github = "normful"
linkedin = "normansue"
twitter = "normful"

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css"
