name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout code
        uses: nschloe/action-checkout-with-lfs-cache@v1
      - name: Run zola build and zola check
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          BUILD_ONLY: true

          # Disable checking of external links. You should occasionally check
          # them yourself locally by running `zola check`. But I think it's not
          # necessary to block deploys here if an external link is temporarily
          # unaccessible.
          CHECK_LINKS: false 
      - name: Setup Node.js with npm dependencies caching
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install npm modules (including Vercel CLI)
        run: npm ci
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --debug --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
